gui:
  language: en
  timeFormat: 02 Jan 06
  shortTimeFormat: 3:04PM
  showListFooter: false
  showFileTree: true # Display as tree, use ~ to swap between tree and flat
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false # Hide bottom bar with instructions
  showPanelJumps: false # If true, show jump-to-window keybindings in window titles.
  nerdFontsVersion: 3
  showFileIcons: true
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: onlyArrow
  splitDiff: auto
  filterMode: fuzzy
  quitOnTopLevelReturn: false
  confirmOnQuit: true
  statusPanelView: allBranchesLog
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: true

  theme:
    selectedLineBgColor:
      - underline
  authorColors:
    "Blake Williams": magenta
    "*": blue
